"""R6: freeze the collected test inventory and the expected per-lane skips, and verify a
run against it.

`EM2-AC-REMEDIATION-DECISION-0001` criterion R6 requires the inventory to be frozen
BEFORE the lanes run, and defines a clean run as: collection matching that inventory,
zero failures and errors, every mandatory routing/refusal test executed, and every
optional-provider test either executed or skipped for the R5 reason.

Usage:
    python -m tests.lanes.freeze_inventory freeze  <out.json>
    python -m tests.lanes.freeze_inventory verify  <frozen.json> <report.json> <lane>

`freeze` records the collected node ids. `verify` compares a pytest JSON-ish report the
caller produces (see the workflow) against the frozen set and the lane's expectations.
Neither command runs tests; collection is side-effect free.
"""
from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

SDK = Path(__file__).resolve().parents[2]

# Tests that MUST execute (never skip) in the lane named as their value.
MANDATORY: dict[str, str] = {
    "tests/test_shipped_default_routing.py": "ordinary",
    "tests/test_shipped_default_live_paths.py::TestMcpBoundaryUnderShippedDefault": "ordinary",
    "tests/test_shipped_default_live_paths.py::TestLiveGateRefusesWhenNoRuntimeExists":
        "runtime-absent",
}

# Suites gated behind an E2E flag: expected to be COLLECTED everywhere but only to RUN in
# the runtime-present lane.
E2E_GATED = (
    "tests/test_sandbox_e2e.py",
    "tests/test_agent_sandbox_e2e.py",
    "tests/test_egress_e2e.py",
)

# Optional-provider suites: under the R5 contract each case runs only when BOTH its module
# and its credential exist, and otherwise skips with a reason naming that contract.
OPTIONAL_PROVIDER = (
    "tests/test_provider_matrix.py",
    "tests/test_e2e_runtime.py",
)

# A skip in an optional-provider suite must name the precondition it lacks.
PRECONDITION_WORDS = (
    "anthropic", "provider", "key", "credential", "module", "package",
    "not set", "not available", "base_url", "base url", "oauth", "install",
    "set agentnode",
)


def collect() -> list[str]:
    out = subprocess.run(
        [sys.executable, "-m", "pytest", "--collect-only", "-q", "-p", "no:randomly", "tests"],
        cwd=SDK, capture_output=True, text=True,
    )
    ids = [ln.strip() for ln in out.stdout.splitlines()
           if ln.strip().startswith("tests/") and "::" in ln]
    if not ids:
        print(out.stdout[-4000:], file=sys.stderr)
        raise SystemExit("collection produced no node ids")
    return sorted(set(ids))


def cmd_freeze(path: str) -> int:
    ids = collect()
    doc = {
        "schema": 1,
        "note": (
            "Frozen collected inventory for the R6 lanes. Generated by collection only; no "
            "test was executed. A lane whose collection differs from this set is not a clean "
            "run, regardless of its pass count."
        ),
        "count": len(ids),
        "mandatory": MANDATORY,
        "e2e_gated_prefixes": list(E2E_GATED),
        "optional_provider_prefixes": list(OPTIONAL_PROVIDER),
        "node_ids": ids,
    }
    Path(path).write_text(json.dumps(doc, indent=2) + "\n", encoding="utf-8")
    print(f"frozen {len(ids)} node ids -> {path}")
    return 0


def cmd_verify(frozen_path: str, report_path: str, lane: str) -> int:
    frozen = json.loads(Path(frozen_path).read_text(encoding="utf-8"))
    report = json.loads(Path(report_path).read_text(encoding="utf-8"))
    outcomes: dict[str, str] = report["outcomes"]
    reasons: dict[str, str] = report.get("skip_reasons", {})

    problems: list[str] = []

    collected = set(outcomes)
    expected = set(frozen["node_ids"])
    # The runtime-absent job deliberately runs only the live-gate file: a container
    # runtime is removed from that job, so the rest of the suite is not its subject.
    # It is verified as a SUBSET — every collected id must be known, the mandatory
    # refusal must have executed, and there must be no failure — but absence of the
    # other ids is expected rather than a defect.
    subset_lane = lane == "runtime-absent"
    missing = [] if subset_lane else sorted(expected - collected)
    extra = sorted(collected - expected)
    if missing:
        problems.append(f"{len(missing)} node id(s) in the frozen inventory were not collected: "
                        + ", ".join(missing[:10]))
    if extra:
        problems.append(f"{len(extra)} node id(s) collected that the inventory does not contain: "
                        + ", ".join(extra[:10]))

    bad = sorted(n for n, o in outcomes.items() if o in ("failed", "error"))
    if bad:
        problems.append(f"{len(bad)} failure(s)/error(s): " + ", ".join(bad[:10]))

    for prefix, want_lane in frozen["mandatory"].items():
        if want_lane != lane:
            continue
        hits = [n for n in outcomes if n.startswith(prefix)]
        if not hits:
            problems.append(f"mandatory {prefix} was not collected in lane {lane}")
            continue
        skipped = [n for n in hits if outcomes[n] == "skipped"]
        if skipped:
            problems.append(f"mandatory {prefix} skipped in lane {lane}: " + ", ".join(skipped[:5]))

    for n, o in outcomes.items():
        if o != "skipped":
            continue
        if n.startswith(tuple(frozen["optional_provider_prefixes"])):
            r = reasons.get(n, "").lower()
            # A skip in these suites is acceptable only when it NAMES the precondition it
            # is missing. That is what distinguishes an intended skip from a masked import
            # failure — the defect R5 was raised to fix. The vocabulary covers the module
            # and credential of the R5 contract plus the other declared preconditions these
            # suites already gate on (a base URL, an explicit opt-in flag).
            if not any(w in r for w in PRECONDITION_WORDS):
                problems.append(f"optional-provider skip without a named precondition: {n} -> {r!r}")

    if problems:
        print("LANE %s: NOT CLEAN" % lane)
        for p in problems:
            print("  - " + p)
        return 1
    print("LANE %s: CLEAN (%d collected, matches the frozen inventory)" % (lane, len(collected)))
    return 0


def main(argv: list[str]) -> int:
    if len(argv) >= 3 and argv[1] == "freeze":
        return cmd_freeze(argv[2])
    if len(argv) >= 5 and argv[1] == "verify":
        return cmd_verify(argv[2], argv[3], argv[4])
    print(__doc__)
    return 2


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
