"use client";

import { useState, useEffect } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import {
  type BuilderResult,
  BUILDER_EXAMPLES as EXAMPLES,
  generateSkill,
  buildArtifact,
} from "@/lib/builder-utils";

/* ------------------------------------------------------------------ */
/*  Component                                                          */
/* ------------------------------------------------------------------ */

export default function BuilderPage() {
  const router = useRouter();
  const [description, setDescription] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [result, setResult] = useState<BuilderResult | null>(null);
  const [activeTab, setActiveTab] = useState<"manifest" | "code" | "preview">(
    "manifest"
  );
  const [copied, setCopied] = useState<string | null>(null);

  /* ---- Warn before leaving with unsaved result ---- */
  useEffect(() => {
    if (!result) return;
    const handler = (e: BeforeUnloadEvent) => { e.preventDefault(); };
    window.addEventListener("beforeunload", handler);
    return () => window.removeEventListener("beforeunload", handler);
  }, [result]);

  /* ---- Generate ---- */
  async function handleGenerate() {
    if (description.trim().length < 10) {
      setError(
        "Please describe your capability in more detail (at least 10 characters)."
      );
      return;
    }
    setLoading(true);
    setError("");
    setResult(null);

    const res = await generateSkill(description);
    if (res.ok && res.data) {
      setResult(res.data);
      setActiveTab("manifest");
    } else {
      setError(res.error || "Generation failed.");
    }
    setLoading(false);
  }

  /* ---- Copy helper ---- */
  function copyToClipboard(text: string, label: string) {
    navigator.clipboard.writeText(text);
    setCopied(label);
    setTimeout(() => setCopied(null), 2000);
  }

  /* ---- Download scaffold ---- */
  function downloadScaffold() {
    if (!result) return;
    let content = `# ${result.metadata.package_name}\n# Generated by AgentNode Builder\n\n`;
    content += `# --- manifest.yaml ---\n${result.manifest_yaml}\n\n`;
    for (const f of result.code_files) {
      content += `# --- ${f.path} ---\n${f.content}\n\n`;
    }
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${result.metadata.package_id}-scaffold.txt`;
    a.click();
    URL.revokeObjectURL(url);
  }

  /* ---- Publish: build artifact and navigate ---- */
  const [publishing, setPublishing] = useState(false);
  async function handlePublish() {
    if (!result) return;
    setPublishing(true);
    try {
      const artifactBlob = await buildArtifact(
        result.metadata.package_id,
        result.manifest_json,
        result.code_files,
      );

      // Store manifest + artifact in sessionStorage, then navigate
      const reader = new FileReader();
      reader.onload = () => {
        sessionStorage.setItem("publish_prefill", JSON.stringify({
          source: "builder",
          manifestText: JSON.stringify(result.manifest_json, null, 2),
        }));
        sessionStorage.setItem("publish_prefill_artifact", JSON.stringify({
          artifactFiles: reader.result as string,
          artifactName: `${result.metadata.package_id}.tar.gz`,
        }));
        router.push("/publish?from=builder");
      };
      reader.readAsDataURL(artifactBlob);
    } catch {
      // Fallback: navigate with just the manifest
      sessionStorage.setItem("publish_prefill", JSON.stringify({
        source: "builder",
        manifestText: JSON.stringify(result.manifest_json, null, 2),
      }));
      router.push("/publish?from=builder");
    } finally {
      setPublishing(false);
    }
  }

  /* ---- Share on X ---- */
  function shareOnX() {
    if (!result) return;
    const text = `I just built an AI agent skill in 30 seconds.\n\n"${result.metadata.package_name}"\n${description.slice(0, 80)}\n\nBuilt with @agentnode\nhttps://agentnode.net/builder`;
    window.open(
      `https://x.com/intent/tweet?text=${encodeURIComponent(text)}`,
      "_blank"
    );
  }

  return (
    <main className="min-h-screen bg-background">
      {/* ============================================================ */}
      {/* Hero                                                          */}
      {/* ============================================================ */}
      <section className="relative overflow-hidden border-b border-border">
        <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-primary/10 via-transparent to-transparent" />
        <div className="relative mx-auto max-w-4xl px-4 sm:px-6 pt-16 pb-6 text-center">
          <div className="mb-4 inline-flex items-center gap-2 rounded-full border border-primary/30 bg-primary/5 px-4 py-1.5 text-xs font-medium text-primary">
            <span className="font-mono">&gt;_</span> Agent Skill Generator
          </div>
          <h1 className="text-4xl font-bold leading-tight tracking-tight text-foreground sm:text-5xl">
            <span className="text-primary">Agent Skill Generator</span>
            <br />
            Build Skills for Any Agent
          </h1>
          <p className="mx-auto mt-5 max-w-2xl text-lg text-muted">
            Describe what your agent should do — get a fully working ANP package
            with code, schema and entrypoints. Ready to edit, run and publish.
          </p>
        </div>
      </section>

      {/* ============================================================ */}
      {/* Input Section                                                 */}
      {/* ============================================================ */}
      <section className="border-b border-border">
        <div className="mx-auto max-w-3xl px-4 sm:px-6 py-10">
          <label className="mb-2 block text-sm font-semibold text-foreground">
            Describe the capability you want to create
          </label>
          <textarea
            value={description}
            onChange={(e) => setDescription(e.target.value)}
            placeholder='e.g. "A tool that extracts email addresses from a webpage and returns them as a list"'
            rows={4}
            className="w-full rounded-xl border border-border bg-card px-4 py-3 text-sm text-foreground placeholder:text-muted/60 focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary/30 resize-none"
            onKeyDown={(e) => {
              if (e.key === "Enter" && (e.metaKey || e.ctrlKey))
                handleGenerate();
            }}
          />

          {/* Example chips */}
          <div className="mt-3 flex flex-wrap gap-2">
            <span className="text-xs text-muted">Try:</span>
            {EXAMPLES.slice(0, 4).map((ex) => (
              <button
                key={ex}
                onClick={() => setDescription(ex)}
                className="rounded-full border border-border bg-card px-3 py-1 text-xs text-muted transition-colors hover:border-primary/30 hover:text-foreground"
              >
                {ex.length > 45 ? ex.slice(0, 45) + "\u2026" : ex}
              </button>
            ))}
          </div>

          {/* Generate button */}
          <div className="mt-6">
            <button
              onClick={handleGenerate}
              disabled={loading || description.trim().length < 10}
              className="rounded-xl bg-primary px-8 py-3 text-sm font-semibold text-white transition-all hover:bg-primary/90 disabled:opacity-40 disabled:cursor-not-allowed"
            >
              {loading ? (
                <span className="flex items-center gap-2">
                  <span className="inline-block h-4 w-4 animate-spin rounded-full border-2 border-white/30 border-t-white" />
                  Generating&hellip;
                </span>
              ) : (
                "Generate capability"
              )}
            </button>
            <span className="ml-3 text-xs text-muted">Ctrl+Enter</span>
          </div>

          {error && (
            <div className="mt-4 rounded-lg border border-red-500/30 bg-red-500/5 px-4 py-3 text-sm text-red-400">
              {error}
            </div>
          )}
        </div>
      </section>

      {/* ============================================================ */}
      {/* Result Section                                                */}
      {/* ============================================================ */}
      {result && (
        <>
          <section className="border-b border-border bg-card/30">
            <div className="mx-auto max-w-4xl px-4 sm:px-6 py-10">
              {/* Success header */}
              <div className="mb-6 flex items-start gap-4">
                <div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-full bg-green-500/10">
                  <svg
                    className="h-6 w-6 text-green-400"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                    strokeWidth={2}
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      d="M5 13l4 4L19 7"
                    />
                  </svg>
                </div>
                <div>
                  <h2 className="text-xl font-bold text-foreground">
                    Your capability is ready
                  </h2>
                  <p className="mt-1 text-sm text-muted">
                    {result.metadata.package_name} &mdash;{" "}
                    {result.metadata.tool_count} tool
                    {result.metadata.tool_count > 1 ? "s" : ""} generated
                  </p>
                </div>
                {result.metadata.publish_ready && (
                  <span className="ml-auto rounded-full bg-green-500/10 px-3 py-1 text-xs font-medium text-green-400">
                    Publish-ready
                  </span>
                )}
              </div>

              {/* Info cards */}
              <div className="mb-6 grid gap-3 sm:grid-cols-4">
                <div className="rounded-lg border border-border bg-card px-4 py-3">
                  <div className="text-xs font-medium uppercase tracking-wider text-muted">
                    Package ID
                  </div>
                  <div className="mt-1 text-sm font-semibold text-foreground font-mono">
                    {result.metadata.package_id}
                  </div>
                </div>
                <div className="rounded-lg border border-border bg-card px-4 py-3">
                  <div className="text-xs font-medium uppercase tracking-wider text-muted">
                    Tools
                  </div>
                  <div className="mt-1 text-sm font-semibold text-foreground">
                    {result.metadata.tool_count}
                  </div>
                </div>
                <div className="rounded-lg border border-border bg-card px-4 py-3">
                  <div className="text-xs font-medium uppercase tracking-wider text-muted">
                    Capabilities
                  </div>
                  <div className="mt-1 text-sm font-semibold text-foreground">
                    {result.metadata.detected_capability_ids.length}
                  </div>
                </div>
                <div className="rounded-lg border border-border bg-card px-4 py-3">
                  <div className="text-xs font-medium uppercase tracking-wider text-muted">
                    Format
                  </div>
                  <div className="mt-1 text-sm font-semibold text-primary">
                    ANP v0.2
                  </div>
                </div>
              </div>

              {/* Capability IDs */}
              <div className="mb-6">
                <h3 className="mb-2 text-xs font-semibold uppercase tracking-wider text-muted">
                  Detected Capabilities
                </h3>
                <div className="flex flex-wrap gap-2">
                  {result.metadata.detected_capability_ids.map((cap) => (
                    <span
                      key={cap}
                      className="rounded-full border border-primary/30 bg-primary/5 px-3 py-1 text-xs font-medium text-primary"
                    >
                      {cap}
                    </span>
                  ))}
                </div>
              </div>

              {/* Warnings */}
              {result.metadata.warnings.length > 0 && (
                <div className="mb-6 rounded-lg border border-yellow-500/30 bg-yellow-500/5 px-4 py-3">
                  {result.metadata.warnings.map((w, i) => (
                    <p key={i} className="text-sm text-yellow-400">
                      {w}
                    </p>
                  ))}
                </div>
              )}

              {/* Tabs */}
              <div className="mb-4 flex gap-1 border-b border-border">
                {(
                  [
                    { key: "manifest", label: "Manifest" },
                    { key: "code", label: "Code" },
                    { key: "preview", label: "Preview" },
                  ] as const
                ).map((tab) => (
                  <button
                    key={tab.key}
                    onClick={() => setActiveTab(tab.key)}
                    className={`border-b-2 px-4 py-2.5 text-sm font-medium transition-colors ${
                      activeTab === tab.key
                        ? "border-primary text-foreground"
                        : "border-transparent text-muted hover:text-foreground"
                    }`}
                  >
                    {tab.label}
                  </button>
                ))}
              </div>

              {/* Tab: Manifest */}
              {activeTab === "manifest" && (
                <div className="relative overflow-hidden rounded-xl border border-border bg-[#0d1117]">
                  <div className="flex items-center justify-between border-b border-border/50 px-4 py-2">
                    <span className="font-mono text-xs text-muted">
                      manifest.yaml
                    </span>
                    <button
                      onClick={() =>
                        copyToClipboard(result.manifest_yaml, "manifest")
                      }
                      className="rounded px-2.5 py-1 text-xs text-muted transition-colors hover:bg-white/10 hover:text-foreground"
                    >
                      {copied === "manifest" ? "Copied!" : "Copy"}
                    </button>
                  </div>
                  <pre className="max-h-96 overflow-auto p-4 font-mono text-xs leading-relaxed text-gray-300">
                    {result.manifest_yaml}
                  </pre>
                </div>
              )}

              {/* Tab: Code */}
              {activeTab === "code" && (
                <div className="space-y-4">
                  {result.code_files.map((file) => (
                    <div
                      key={file.path}
                      className="relative overflow-hidden rounded-xl border border-border bg-[#0d1117]"
                    >
                      <div className="flex items-center justify-between border-b border-border/50 px-4 py-2">
                        <span className="font-mono text-xs text-muted">
                          {file.path}
                        </span>
                        <button
                          onClick={() =>
                            copyToClipboard(file.content, file.path)
                          }
                          className="rounded px-2.5 py-1 text-xs text-muted transition-colors hover:bg-white/10 hover:text-foreground"
                        >
                          {copied === file.path ? "Copied!" : "Copy"}
                        </button>
                      </div>
                      <pre className="max-h-80 overflow-auto p-4 font-mono text-xs leading-relaxed text-gray-300">
                        {file.content}
                      </pre>
                    </div>
                  ))}
                </div>
              )}

              {/* Tab: Preview */}
              {activeTab === "preview" && (
                <div className="rounded-xl border border-border bg-card p-6">
                  <div className="grid gap-4 sm:grid-cols-2">
                    <div>
                      <div className="text-xs font-medium uppercase tracking-wider text-muted">
                        Package Name
                      </div>
                      <div className="mt-1 font-semibold text-foreground">
                        {result.metadata.package_name}
                      </div>
                    </div>
                    <div>
                      <div className="text-xs font-medium uppercase tracking-wider text-muted">
                        Package ID
                      </div>
                      <div className="mt-1 font-mono text-sm text-foreground">
                        {result.metadata.package_id}
                      </div>
                    </div>
                    <div>
                      <div className="text-xs font-medium uppercase tracking-wider text-muted">
                        Capabilities
                      </div>
                      <div className="mt-1 flex flex-wrap gap-1">
                        {result.metadata.detected_capability_ids.map((c) => (
                          <span
                            key={c}
                            className="rounded bg-primary/10 px-2 py-0.5 text-xs text-primary"
                          >
                            {c}
                          </span>
                        ))}
                      </div>
                    </div>
                    <div>
                      <div className="text-xs font-medium uppercase tracking-wider text-muted">
                        Standard
                      </div>
                      <div className="mt-1 text-foreground">
                        ANP v0.2 &mdash; LangChain, CrewAI, MCP, Python
                      </div>
                    </div>
                    <div className="sm:col-span-2">
                      <div className="text-xs font-medium uppercase tracking-wider text-muted">
                        Files included
                      </div>
                      <div className="mt-1 space-y-1">
                        {result.code_files.map((f) => (
                          <div
                            key={f.path}
                            className="font-mono text-sm text-muted"
                          >
                            {f.path}
                          </div>
                        ))}
                      </div>
                    </div>
                  </div>
                </div>
              )}

              {/* Publish CTA */}
              <div className="mt-8 rounded-xl border border-primary/30 bg-gradient-to-r from-primary/5 to-primary/10 p-6">
                <div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between">
                  <div>
                    <h3 className="text-lg font-bold text-foreground">
                      Ready to publish?
                    </h3>
                    <p className="mt-1 text-sm text-muted">
                      Publish this package on AgentNode and make it available to
                      every AI agent.
                    </p>
                  </div>
                  <button
                    onClick={handlePublish}
                    disabled={publishing}
                    className="shrink-0 rounded-lg bg-primary px-6 py-2.5 text-center text-sm font-semibold text-white transition-colors hover:bg-primary/90 disabled:opacity-60"
                  >
                    {publishing ? (
                      <span className="flex items-center gap-2">
                        <span className="inline-block h-4 w-4 animate-spin rounded-full border-2 border-white/30 border-t-white" />
                        Preparing&hellip;
                      </span>
                    ) : (
                      "Publish this package"
                    )}
                  </button>
                </div>
              </div>

              {/* Secondary actions */}
              <div className="mt-4 flex flex-wrap gap-3">
                <button
                  onClick={() =>
                    copyToClipboard(result.manifest_yaml, "manifest-cta")
                  }
                  className="rounded-lg border border-border px-4 py-2 text-sm text-muted transition-colors hover:text-foreground"
                >
                  {copied === "manifest-cta" ? "Copied!" : "Copy manifest"}
                </button>
                <button
                  onClick={downloadScaffold}
                  className="rounded-lg border border-border px-4 py-2 text-sm text-muted transition-colors hover:text-foreground"
                >
                  Download scaffold
                </button>
                <button
                  onClick={shareOnX}
                  className="rounded-lg border border-border px-4 py-2 text-sm text-muted transition-colors hover:text-foreground"
                >
                  Share on X
                </button>
                <button
                  onClick={() => {
                    setResult(null);
                    setDescription("");
                  }}
                  className="rounded-lg border border-border px-4 py-2 text-sm text-muted transition-colors hover:text-foreground"
                >
                  Start over
                </button>
              </div>
            </div>
          </section>

          {/* ======================================================== */}
          {/* Use this skill everywhere                                 */}
          {/* ======================================================== */}
          <section className="border-b border-border">
            <div className="mx-auto max-w-4xl px-4 sm:px-6 py-10">
              <h3 className="mb-2 text-lg font-bold text-foreground">
                Works with any agent framework
              </h3>
              <p className="mb-6 text-sm text-muted">
                One ANP package, every framework. No rewrites needed.
              </p>
              <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
                {[
                  {
                    label: "AgentNode SDK",
                    code: `from agentnode_sdk import AgentNodeClient\nfrom agentnode_sdk.installer import load_tool\n\nclient = AgentNodeClient()\nclient.install("${result.metadata.package_id}")\n\ntool = load_tool("${result.metadata.package_id}")\nresult = tool({"input": "...  "})`,
                  },
                  {
                    label: "LLM Runtime",
                    code: `from agentnode_sdk import AgentNodeRuntime\n\n# LLM discovers and uses your tool\nruntime = AgentNodeRuntime()\nresult = runtime.run(\n    provider="openai",\n    client=OpenAI(),\n    model="gpt-4o",\n    messages=[...],\n)`,
                  },
                  {
                    label: "LangChain",
                    code: `from agentnode_langchain import as_langchain_tool\n\ntool = as_langchain_tool("${result.metadata.package_id}")`,
                  },
                  {
                    label: "MCP",
                    code: `from agentnode_mcp import as_mcp_tool\n\ntool = as_mcp_tool("${result.metadata.package_id}")`,
                  },
                  {
                    label: "CLI",
                    code: `agentnode install ${result.metadata.package_id}`,
                  },
                ].map((fw) => (
                  <div
                    key={fw.label}
                    className="overflow-hidden rounded-lg border border-border bg-[#0d1117]"
                  >
                    <div className="flex items-center justify-between border-b border-border/50 px-3 py-1.5">
                      <span className="text-xs font-medium text-muted">
                        {fw.label}
                      </span>
                      <button
                        onClick={() =>
                          copyToClipboard(fw.code, `fw-${fw.label}`)
                        }
                        className="rounded px-1.5 py-0.5 text-[10px] text-muted transition-colors hover:text-foreground"
                      >
                        {copied === `fw-${fw.label}` ? "Copied!" : "Copy"}
                      </button>
                    </div>
                    <pre className="p-3 font-mono text-[11px] leading-relaxed text-gray-400">
                      {fw.code}
                    </pre>
                  </div>
                ))}
              </div>
            </div>
          </section>
        </>
      )}

      {/* ============================================================ */}
      {/* How It Works (only shown before generation)                   */}
      {/* ============================================================ */}
      {!result && (
        <>
          <section className="border-b border-border">
            <div className="mx-auto max-w-5xl px-4 sm:px-6 py-16">
              <h2 className="mb-10 text-center text-2xl font-bold text-foreground sm:text-3xl">
                How it works
              </h2>
              <div className="grid gap-8 sm:grid-cols-3">
                {[
                  {
                    step: "1",
                    title: "Describe",
                    desc: "Tell us what your agent capability should do in plain language.",
                    icon: (
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10"
                      />
                    ),
                  },
                  {
                    step: "2",
                    title: "Generate",
                    desc: "Get a complete ANP v0.2 package with manifest, code, and schemas.",
                    icon: (
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        d="M9.813 15.904L9 18.75l-.813-2.846a4.5 4.5 0 00-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 003.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 003.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 00-3.09 3.09zM18.259 8.715L18 9.75l-.259-1.035a3.375 3.375 0 00-2.455-2.456L14.25 6l1.036-.259a3.375 3.375 0 002.455-2.456L18 2.25l.259 1.035a3.375 3.375 0 002.455 2.456L21.75 6l-1.036.259a3.375 3.375 0 00-2.455 2.456zM16.894 20.567L16.5 21.75l-.394-1.183a2.25 2.25 0 00-1.423-1.423L13.5 18.75l1.183-.394a2.25 2.25 0 001.423-1.423l.394-1.183.394 1.183a2.25 2.25 0 001.423 1.423l1.183.394-1.183.394a2.25 2.25 0 00-1.423 1.423z"
                      />
                    ),
                  },
                  {
                    step: "3",
                    title: "Edit & Publish",
                    desc: "Review the generated code, customize it, and publish to AgentNode.",
                    icon: (
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        d="M3 16.5v2.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5m-13.5-9L12 3m0 0l4.5 4.5M12 3v13.5"
                      />
                    ),
                  },
                ].map((item) => (
                  <div
                    key={item.step}
                    className="rounded-xl border border-border bg-card p-6 text-center"
                  >
                    <div className="mx-auto mb-4 flex h-12 w-12 items-center justify-center rounded-full bg-primary/10">
                      <svg
                        className="h-6 w-6 text-primary"
                        fill="none"
                        viewBox="0 0 24 24"
                        stroke="currentColor"
                        strokeWidth={1.5}
                      >
                        {item.icon}
                      </svg>
                    </div>
                    <div className="mb-1 text-xs font-bold uppercase tracking-wider text-primary">
                      Step {item.step}
                    </div>
                    <h3 className="mb-2 text-lg font-bold text-foreground">
                      {item.title}
                    </h3>
                    <p className="text-sm text-muted">{item.desc}</p>
                  </div>
                ))}
              </div>
            </div>
          </section>

          {/* Two ways to create */}
          <section className="border-b border-border">
            <div className="mx-auto max-w-4xl px-4 sm:px-6 py-16">
              <h2 className="mb-10 text-center text-2xl font-bold text-foreground">
                Two ways to create packages
              </h2>
              <div className="grid gap-6 sm:grid-cols-2">
                <div className="rounded-xl border border-border bg-card p-6">
                  <div className="mb-4 text-sm font-semibold uppercase tracking-wider text-primary">
                    Have an idea?
                  </div>
                  <h3 className="mb-2 text-lg font-bold text-foreground">
                    Capability Builder
                  </h3>
                  <p className="mb-4 text-sm text-muted">
                    Describe what your tool should do and get a complete scaffold
                    with manifest, code, and schemas.
                  </p>
                  <ul className="space-y-2 text-sm">
                    {[
                      "Start from a description",
                      "Get production-ready structure",
                      "Editable code scaffold",
                      "Valid ANP v0.2 output",
                    ].map((t) => (
                      <li
                        key={t}
                        className="flex items-center gap-2 text-muted"
                      >
                        <span className="text-green-400">&#10003;</span> {t}
                      </li>
                    ))}
                  </ul>
                  <div className="mt-5">
                    <span className="rounded-full bg-primary/10 px-3 py-1 text-xs font-medium text-primary">
                      You are here
                    </span>
                  </div>
                </div>
                <div className="rounded-xl border border-border bg-card p-6">
                  <div className="mb-4 text-sm font-semibold uppercase tracking-wider text-muted">
                    Have code?
                  </div>
                  <h3 className="mb-2 text-lg font-bold text-foreground">
                    Import Tool
                  </h3>
                  <p className="mb-4 text-sm text-muted">
                    Paste existing LangChain, MCP, OpenAI, or CrewAI code and
                    convert it to an ANP package.
                  </p>
                  <ul className="space-y-2 text-sm">
                    {[
                      "Start from existing code",
                      "Auto-detect tools & schemas",
                      "Multi-framework support",
                      "Instant conversion",
                    ].map((t) => (
                      <li
                        key={t}
                        className="flex items-center gap-2 text-muted"
                      >
                        <span className="text-green-400">&#10003;</span> {t}
                      </li>
                    ))}
                  </ul>
                  <div className="mt-5">
                    <Link
                      href="/import"
                      className="rounded-full border border-border px-3 py-1 text-xs font-medium text-muted transition-colors hover:text-foreground"
                    >
                      Go to Import
                    </Link>
                  </div>
                </div>
              </div>
            </div>
          </section>

          {/* Inspiration */}
          <section className="border-b border-border">
            <div className="mx-auto max-w-4xl px-4 sm:px-6 py-16">
              <h2 className="mb-6 text-center text-2xl font-bold text-foreground">
                Need inspiration?
              </h2>
              <p className="mb-8 text-center text-sm text-muted">
                Click any example to try it instantly
              </p>
              <div className="grid gap-3 sm:grid-cols-2">
                {EXAMPLES.map((ex) => (
                  <button
                    key={ex}
                    onClick={() => {
                      setDescription(ex);
                      window.scrollTo({ top: 0, behavior: "smooth" });
                    }}
                    className="rounded-lg border border-border bg-card px-4 py-3 text-left text-sm text-muted transition-colors hover:border-primary/30 hover:text-foreground"
                  >
                    {ex}
                  </button>
                ))}
              </div>
            </div>
          </section>
        </>
      )}
    </main>
  );
}
