"""AgentNode compatibility data and model recommendations.

Auto-generated by sdk/scripts/generate_compatibility_artifacts.py
Manual edits to _RECOMMENDED are preserved across regeneration.
"""
from __future__ import annotations


_TIER_ORDER = {"S": 0, "A": 1, "B": 2, "C": 3, "F": 4}


def _tier_passes(tier: str, minimum: str) -> bool:
    """Check if a tier meets the minimum requirement."""
    return _TIER_ORDER.get(tier, 99) <= _TIER_ORDER.get(minimum, 0)


# Generated from merged_matrix.json — provider -> [(model, tier), ...]
_TIER_DATA: dict[str, list[tuple[str, str]]] = {
    "ai21": [("jamba-large-1.7", "C")],
    "alibaba": [("tongyi-deepresearch-30b-a3b", "S")],
    "allenai": [("olmo-3.1-32b-instruct", "S")],
    "amazon": [("nova-2-lite-v1", "S"), ("nova-lite-v1", "S"), ("nova-micro-v1", "S"), ("nova-premier-v1", "S"), ("nova-pro-v1", "S")],
    "anthropic": [("claude-3-haiku", "S"), ("claude-3.7-sonnet", "S"), ("claude-haiku-4.5", "S"), ("claude-opus-4", "S"), ("claude-opus-4.1", "S"), ("claude-opus-4.5", "S"), ("claude-opus-4.6", "S"), ("claude-sonnet-4", "S"), ("claude-sonnet-4.5", "S"), ("claude-sonnet-4.6", "S")],
    "arcee-ai": [("trinity-mini", "C")],
    "bytedance-seed": [("seed-1.6", "S"), ("seed-1.6-flash", "S"), ("seed-2.0-lite", "S"), ("seed-2.0-mini", "S")],
    "cohere": [("command-r-08-2024", "S"), ("command-r-plus-08-2024", "S")],
    "deepseek": [("deepseek-chat", "S"), ("deepseek-chat-v3-0324", "S"), ("deepseek-chat-v3.1", "S"), ("deepseek-r1", "S"), ("deepseek-r1-0528", "A"), ("deepseek-v3.1-terminus", "S"), ("deepseek-v3.2", "S"), ("deepseek-v3.2-exp", "S")],
    "essentialai": [("rnj-1-instruct", "S")],
    "google": [("gemini-2.0-flash-001", "S"), ("gemini-2.0-flash-lite-001", "S"), ("gemini-2.5-flash", "S"), ("gemini-2.5-flash-lite", "S"), ("gemini-2.5-pro", "S"), ("gemma-4-26b-a4b-it", "S"), ("gemma-4-31b-it", "S")],
    "inception": [("mercury", "S"), ("mercury-2", "S"), ("mercury-coder", "S")],
    "kwaipilot": [("kat-coder-pro-v2", "S")],
    "meituan": [("longcat-flash-chat", "C")],
    "meta-llama": [("llama-3-8b-instruct", "S"), ("llama-3.1-70b-instruct", "S"), ("llama-3.1-8b-instruct", "S"), ("llama-3.3-70b-instruct", "S"), ("llama-4-maverick", "S"), ("llama-4-scout", "S")],
    "minimax": [("minimax-m1", "S"), ("minimax-m2", "S"), ("minimax-m2.1", "S"), ("minimax-m2.5", "S"), ("minimax-m2.7", "S")],
    "mistralai": [("codestral-2508", "S"), ("devstral-2512", "S"), ("devstral-medium", "S"), ("devstral-small", "S"), ("ministral-14b-2512", "S"), ("ministral-3b-2512", "S"), ("ministral-8b-2512", "S"), ("mistral-large", "S"), ("mistral-large-2407", "S"), ("mistral-large-2411", "S"), ("mistral-large-2512", "S"), ("mistral-medium-3", "S"), ("mistral-medium-3.1", "S"), ("mistral-nemo", "S"), ("mistral-saba", "S"), ("mistral-small-2603", "S"), ("mistral-small-3.2-24b-instruct", "S"), ("mistral-small-creative", "S"), ("mixtral-8x22b-instruct", "S"), ("mixtral-8x7b-instruct", "F"), ("pixtral-large-2411", "S"), ("voxtral-small-24b-2507", "S")],
    "moonshotai": [("kimi-k2", "S"), ("kimi-k2-0905", "S"), ("kimi-k2.5", "S")],
    "nex-agi": [("deepseek-v3.1-nex-n1", "S")],
    "nvidia": [("llama-3.1-nemotron-70b-instruct", "S"), ("llama-3.3-nemotron-super-49b-v1.5", "S"), ("nemotron-3-nano-30b-a3b", "S"), ("nemotron-nano-9b-v2", "S")],
    "openai": [("gpt-3.5-turbo", "S"), ("gpt-3.5-turbo-0613", "S"), ("gpt-3.5-turbo-16k", "S"), ("gpt-4", "S"), ("gpt-4-turbo", "S"), ("gpt-4.1", "S"), ("gpt-4.1-mini", "S"), ("gpt-4.1-nano", "S"), ("gpt-4o", "S"), ("gpt-4o-2024-05-13", "S"), ("gpt-4o-2024-08-06", "S"), ("gpt-4o-2024-11-20", "S"), ("gpt-4o-mini", "S"), ("gpt-4o-mini-2024-07-18", "S"), ("gpt-5", "S"), ("gpt-5-mini", "S"), ("gpt-5-nano", "S"), ("gpt-5-pro", "S"), ("gpt-5.1", "S"), ("gpt-5.1-chat", "S"), ("gpt-5.2", "S"), ("gpt-5.2-chat", "S"), ("gpt-5.3-chat", "S"), ("gpt-5.4", "S"), ("gpt-5.4-mini", "S"), ("gpt-5.4-nano", "S"), ("gpt-oss-120b", "S"), ("gpt-oss-20b", "S"), ("gpt-oss-safeguard-20b", "B"), ("o1", "S"), ("o3", "S"), ("o3-mini", "S"), ("o3-mini-high", "S"), ("o3-pro", "S"), ("o4-mini", "S"), ("o4-mini-high", "S")],
    "openrouter": [("auto", "S"), ("free", "S")],
    "prime-intellect": [("intellect-3", "S")],
    "qwen": [("qwen-2.5-72b-instruct", "S"), ("qwen-2.5-7b-instruct", "S"), ("qwen-max", "S"), ("qwen-plus", "S"), ("qwen-plus-2025-07-28", "S"), ("qwen-turbo", "S"), ("qwen3-14b", "S"), ("qwen3-235b-a22b", "S"), ("qwen3-235b-a22b-2507", "S"), ("qwen3-30b-a3b", "S"), ("qwen3-30b-a3b-instruct-2507", "S"), ("qwen3-32b", "S"), ("qwen3-8b", "S"), ("qwen3-coder", "S"), ("qwen3-coder-30b-a3b-instruct", "S"), ("qwen3-coder-flash", "S"), ("qwen3-coder-next", "S"), ("qwen3-coder-plus", "S"), ("qwen3-max", "S"), ("qwen3-next-80b-a3b-instruct", "S"), ("qwen3.5-122b-a10b", "S"), ("qwen3.5-27b", "S"), ("qwen3.5-35b-a3b", "S"), ("qwen3.5-397b-a17b", "S"), ("qwen3.5-9b", "S"), ("qwen3.5-flash-02-23", "S"), ("qwen3.5-plus-02-15", "S"), ("qwq-32b", "S")],
    "rekaai": [("reka-edge", "A")],
    "relace": [("relace-search", "S")],
    "stepfun": [("step-3.5-flash", "S")],
    "tngtech": [("deepseek-r1t2-chimera", "S")],
    "upstage": [("solar-pro-3", "S")],
    "x-ai": [("grok-3", "S"), ("grok-3-beta", "S"), ("grok-3-mini", "S"), ("grok-3-mini-beta", "S"), ("grok-4", "S"), ("grok-4-fast", "S"), ("grok-4.1-fast", "S"), ("grok-4.20", "S"), ("grok-code-fast-1", "S")],
    "xiaomi": [("mimo-v2-flash", "S"), ("mimo-v2-omni", "S"), ("mimo-v2-pro", "S")],
    "z-ai": [("glm-4-32b", "S"), ("glm-4.5", "S"), ("glm-4.5-air", "S"), ("glm-4.5v", "S"), ("glm-4.6", "S"), ("glm-4.6v", "S"), ("glm-4.7", "S"), ("glm-4.7-flash", "S"), ("glm-5", "S"), ("glm-5-turbo", "S"), ("glm-5v-turbo", "S")],
}

# Curated recommendations — override layer
_RECOMMENDED: dict[str | None, dict[str, str]] = {
    None: {"best": "gpt-4o", "cheapest": "gpt-4o-mini"},
    "openai": {"best": "gpt-4o", "cheapest": "gpt-4o-mini"},
    "anthropic": {"best": "claude-sonnet-4.6", "cheapest": "claude-haiku-4.5"},
    "google": {"best": "gemini-2.5-flash", "cheapest": "gemini-2.0-flash-001"},
    "mistralai": {"best": "mistral-large", "cheapest": "mistral-nemo"},
    "meta-llama": {"best": "llama-4-maverick", "cheapest": "llama-3.1-8b-instruct"},
    "deepseek": {"best": "deepseek-chat", "cheapest": "deepseek-chat"},
    "qwen": {"best": "qwen3-235b-a22b", "cheapest": "qwen3-30b-a3b"},
    "x-ai": {"best": "grok-4", "cheapest": "grok-3-mini"},
    "cohere": {"best": "command-r-plus-08-2024", "cheapest": "command-r-08-2024"},
    "nvidia": {"best": "llama-3.3-nemotron-super-49b-v1.5", "cheapest": "nemotron-nano-9b-v2"},
    "amazon": {"best": "nova-pro-v1", "cheapest": "nova-micro-v1"},
    "minimax": {"best": "minimax-m2.7", "cheapest": "minimax-m1"},
    "z-ai": {"best": "glm-5", "cheapest": "glm-4.7-flash"},
    "inception": {"best": "mercury-2", "cheapest": "mercury"},
    "moonshotai": {"best": "kimi-k2.5", "cheapest": "kimi-k2"},
    "xiaomi": {"best": "mimo-v2-pro", "cheapest": "mimo-v2-flash"},
    "bytedance-seed": {"best": "seed-1.6", "cheapest": "seed-2.0-mini"},
}


def recommend_model(
    provider: str | None = None,
    *,
    prefer: str = "best",
    minimum_tier: str = "S",
) -> str | None:
    """Recommend a model for a given provider.

    Args:
        provider: Provider name (e.g. "openai", "anthropic"). None for overall best.
        prefer: "best" or "cheapest".
        minimum_tier: Minimum acceptable tier ("S", "A", "B", "C", "F").

    Returns:
        Model name string, or None if no model meets the criteria.

    Raises:
        ValueError: If prefer or minimum_tier is invalid.
    """
    if prefer not in ("best", "cheapest"):
        raise ValueError(f"Unknown prefer value: {prefer!r}. Use 'best' or 'cheapest'.")
    if minimum_tier not in _TIER_ORDER:
        raise ValueError(
            f"Unknown minimum_tier: {minimum_tier!r}. Use one of: {', '.join(_TIER_ORDER)}."
        )

    if provider is not None:
        provider = provider.lower()

    # Try curated recommendation first
    recs = _RECOMMENDED.get(provider)
    if recs:
        candidate = recs.get(prefer)
        if candidate:
            # Verify the candidate meets the minimum tier
            tier_list = _TIER_DATA.get(provider, [])
            for model_name, tier in tier_list:
                if model_name == candidate and _tier_passes(tier, minimum_tier):
                    return candidate

    # Fallback: find best model from tier data that meets minimum
    if provider is None:
        # Overall: check all providers
        for prov, models in _TIER_DATA.items():
            for model_name, tier in models:
                if _tier_passes(tier, minimum_tier):
                    # Return overall curated default if available
                    overall = _RECOMMENDED.get(None, {})
                    fallback = overall.get(prefer)
                    if fallback:
                        return fallback
                    return model_name
        return None

    tier_list = _TIER_DATA.get(provider, [])
    if not tier_list:
        return None

    # Find any model meeting the minimum tier
    for model_name, tier in tier_list:
        if _tier_passes(tier, minimum_tier):
            return model_name

    return None
