"""MCP submission endpoints."""
import copy
import logging
from datetime import datetime, timedelta, timezone
from uuid import UUID, uuid4

from fastapi import APIRouter, Depends, Query, Request
from pydantic import BaseModel, Field
from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.auth.dependencies import require_admin, require_publisher
from app.auth.models import User
from app.database import get_session
from app.shared.exceptions import AppError
from app.shared.rate_limit import rate_limit
from app.mcp.models import McpSubmission, PublisherPackageClaim
from app.mcp.registry_verify import verify_registry, derive_status, normalize_package_name

OWNERSHIP_CLAIM_TTL_DAYS = 180


async def _latest_verified_claim(session: AsyncSession, submission: McpSubmission):
    """Most recent verified ownership claim matching this submission's
    (publisher, registry, normalized package name). Expiry is checked by the
    caller so 'expired' can be distinguished from 'missing'."""
    norm = normalize_package_name(submission.package_registry, submission.package_name)
    return (await session.execute(
        select(PublisherPackageClaim).where(
            PublisherPackageClaim.publisher_id == submission.publisher_id,
            PublisherPackageClaim.registry == submission.package_registry,
            PublisherPackageClaim.package_name_normalized == norm,
            PublisherPackageClaim.status == "verified",
        ).order_by(PublisherPackageClaim.verified_at.desc())
    )).scalars().first()


def _ownership_view(claim: PublisherPackageClaim | None) -> dict:
    """Ownership (package_control) status for the admin UI — independent of
    server_verification.repo_consistency."""
    if claim is None:
        return {"status": "missing", "method": None, "verified_at": None, "expires_at": None}
    expired = claim.expires_at is not None and claim.expires_at <= datetime.now(timezone.utc)
    return {
        "status": "expired" if expired else "verified",
        "method": claim.method,
        "verified_at": claim.verified_at.isoformat() if claim.verified_at else None,
        "expires_at": claim.expires_at.isoformat() if claim.expires_at else None,
    }


router = APIRouter(prefix="/v1/mcp", tags=["mcp"])
admin_router = APIRouter(prefix="/v1/admin/mcp", tags=["admin-mcp"])
logger = logging.getLogger(__name__)

VALID_STATUSES = {"INVALID", "RESOLVED", "TESTED", "REVIEW_NEEDED", "MAINTAINER_ACTION_REQUIRED"}
MAX_SUBMIT_BODY_BYTES = 512_000  # 500 KB


class McpSubmitRequest(BaseModel):
    manifest: dict = Field(..., description="agentnode.yaml manifest (v0.3, runtime=mcp)")
    verification_report: dict = Field(..., description="Output of agentnode mcp verify --json")


class McpSubmitResponse(BaseModel):
    id: str
    status: str
    package_name: str
    message: str


@router.post(
    "/submit",
    response_model=McpSubmitResponse,
    status_code=201,
    dependencies=[Depends(rate_limit(5, 60))],
)
async def submit_mcp(
    request: Request,
    body: McpSubmitRequest,
    user: User = Depends(require_publisher),
    session: AsyncSession = Depends(get_session),
):
    """Submit an MCP server for catalog review.

    Accepts a manifest and its verification report. The report must have been
    generated by `agentnode mcp verify --json`. No code is executed server-side.
    """
    content_length = request.headers.get("content-length")
    if content_length and int(content_length) > MAX_SUBMIT_BODY_BYTES:
        raise AppError("MCP_PAYLOAD_TOO_LARGE", f"Request body must be under {MAX_SUBMIT_BODY_BYTES // 1024} KB", 400)

    manifest = body.manifest
    report = body.verification_report

    if manifest.get("runtime") != "mcp":
        raise AppError("MCP_INVALID_RUNTIME", "Manifest runtime must be 'mcp'", 400)

    mcp_server = manifest.get("mcp_server")
    if not isinstance(mcp_server, dict):
        raise AppError("MCP_MISSING_SERVER", "Manifest must have mcp_server block", 400)

    report_status = report.get("status", "")
    if report_status not in VALID_STATUSES:
        raise AppError("MCP_INVALID_REPORT", f"Verification report status '{report_status}' is not valid", 400)

    if report_status == "INVALID":
        raise AppError("MCP_REPORT_INVALID", "Cannot submit with INVALID verification status. Fix errors first.", 400)

    pkg_name = mcp_server.get("npm_package") or mcp_server.get("pypi_package") or "unknown"
    pkg_registry = "npm" if mcp_server.get("npm_package") else "pypi"
    source_repo = mcp_server.get("source_repo")

    # Server-side re-verification: re-derive registry-checkable facts ourselves.
    # The client report is advisory; this is authoritative. No code is executed.
    server_verification = await verify_registry(manifest)
    # Resolved version is authoritative; fall back to the client claim only if the
    # registry was unavailable and we could not resolve anything.
    pkg_version = server_verification.get("resolved_version") or report.get("package", {}).get("version")

    # Duplicate check: block if an open submission exists for same package+version
    open_statuses = ("pending", "action_required", "needs_changes", "approved")
    existing = (await session.execute(
        select(McpSubmission).where(
            McpSubmission.publisher_id == user.publisher.id,
            McpSubmission.package_name == pkg_name,
            McpSubmission.package_version == pkg_version,
            McpSubmission.status.in_(open_statuses),
        )
    )).scalar_one_or_none()

    if existing:
        if existing.status == "approved":
            raise AppError(
                "MCP_ALREADY_APPROVED",
                f"{pkg_name}@{pkg_version} was already approved (submission {str(existing.id)[:8]}).",
                409,
                details={"existing_submission_id": str(existing.id), "existing_status": existing.status},
            )
        raise AppError(
            "MCP_DUPLICATE_SUBMISSION",
            f"An open submission for {pkg_name}@{pkg_version} already exists (status: {existing.status}). "
            f"Check status: agentnode mcp status {existing.id}",
            409,
            details={"existing_submission_id": str(existing.id), "existing_status": existing.status},
        )

    submission = McpSubmission(
        id=uuid4(),
        publisher_id=user.publisher.id,
        package_name=pkg_name,
        package_registry=pkg_registry,
        package_version=pkg_version,
        source_repo=source_repo,
        manifest_raw=manifest,
        verification_report=report,
        server_verification=server_verification,
        status=derive_status(server_verification, report),
    )
    session.add(submission)
    await session.flush()
    await session.commit()

    logger.info(
        "MCP submission %s by publisher %s: %s (%s, server=%s)",
        submission.id, user.publisher.slug, pkg_name, submission.status,
        server_verification.get("server_status"),
    )

    if submission.status == "pending":
        msg = f"Submission received. {pkg_name} is queued for catalog review."
    else:
        sstatus = server_verification.get("server_status")
        if sstatus == "mismatch":
            reasons = "; ".join(server_verification.get("errors") or []) or "registry contradicts manifest"
            msg = f"Submission received but server verification failed: {reasons}. Fix and resubmit."
        else:
            actions = report.get("actions", [])
            high_count = sum(1 for a in actions if a.get("severity") == "high")
            msg = f"Submission received with {high_count} required action(s). Fix and resubmit for faster review."

    return McpSubmitResponse(
        id=str(submission.id),
        status=submission.status,
        package_name=pkg_name,
        message=msg,
    )


# ---------------------------------------------------------------------------
# Maintainer status endpoint (publisher-scoped)
# ---------------------------------------------------------------------------

class MaintainerSubmissionStatus(BaseModel):
    id: str
    package_name: str
    package_registry: str
    package_version: str | None
    source_repo: str | None
    status: str
    report_status: str | None
    report_summary: str | None
    actions: list[dict] | None
    server_verification: dict | None
    maintainer_feedback: str | None
    reviewed_at: str | None
    published_package_id: str | None
    created_at: str


@router.get(
    "/submissions/{submission_id}",
    response_model=MaintainerSubmissionStatus,
    dependencies=[Depends(rate_limit(20, 60))],
)
async def get_own_submission(
    submission_id: UUID,
    user: User = Depends(require_publisher),
    session: AsyncSession = Depends(get_session),
):
    """Get status of own submission. Publisher-scoped — only the submitting publisher can view."""
    row = (await session.execute(
        select(McpSubmission).where(
            McpSubmission.id == submission_id,
            McpSubmission.publisher_id == user.publisher.id,
        )
    )).scalar_one_or_none()

    if not row:
        raise AppError("MCP_SUBMISSION_NOT_FOUND", "Submission not found or not owned by your publisher", 404)

    report = row.verification_report or {}

    return MaintainerSubmissionStatus(
        id=str(row.id),
        package_name=row.package_name,
        package_registry=row.package_registry,
        package_version=row.package_version,
        source_repo=row.source_repo,
        status=row.status,
        report_status=report.get("status"),
        report_summary=report.get("summary"),
        actions=report.get("actions"),
        server_verification=row.server_verification,
        maintainer_feedback=row.maintainer_feedback,
        reviewed_at=row.reviewed_at.isoformat() if row.reviewed_at else None,
        published_package_id=str(row.published_package_id) if row.published_package_id else None,
        created_at=row.created_at.isoformat() if row.created_at else "",
    )


# ---------------------------------------------------------------------------
# Admin endpoints
# ---------------------------------------------------------------------------

class SubmissionSummary(BaseModel):
    id: str
    package_name: str
    package_registry: str
    package_version: str | None
    source_repo: str | None
    status: str
    report_status: str | None
    server_status: str | None
    report_summary: str | None
    actions_high: int
    actions_medium: int
    tools_count: int
    created_at: str


class SubmissionListResponse(BaseModel):
    submissions: list[SubmissionSummary]
    total: int


class SubmissionDetail(BaseModel):
    id: str
    package_name: str
    package_registry: str
    package_version: str | None
    source_repo: str | None
    status: str
    manifest: dict
    verification_report: dict
    server_verification: dict | None
    ownership: dict
    reviewer_notes: str | None
    maintainer_feedback: str | None
    published_package_id: str | None
    created_at: str
    updated_at: str


class ReviewRequest(BaseModel):
    status: str = Field(..., description="New status: approved, rejected, needs_changes")
    notes: str | None = Field(None, description="Internal reviewer notes (admin-only)")
    maintainer_feedback: str | None = Field(None, description="Message visible to the submitting maintainer")


class ReviewResponse(BaseModel):
    id: str
    status: str
    message: str


ADMIN_VALID_STATUSES = {"approved", "rejected", "needs_changes", "pending", "action_required"}


@admin_router.get(
    "/submissions",
    response_model=SubmissionListResponse,
    dependencies=[Depends(rate_limit(30, 60))],
)
async def list_submissions(
    status: str | None = Query(None),
    page: int = Query(1, ge=1),
    per_page: int = Query(20, ge=1, le=100),
    user: User = Depends(require_admin),
    session: AsyncSession = Depends(get_session),
):
    """List MCP submissions for admin review."""
    query = select(McpSubmission).order_by(McpSubmission.created_at.desc())
    count_query = select(func.count(McpSubmission.id))

    if status:
        query = query.where(McpSubmission.status == status)
        count_query = count_query.where(McpSubmission.status == status)

    total = (await session.execute(count_query)).scalar() or 0
    query = query.offset((page - 1) * per_page).limit(per_page)
    rows = (await session.execute(query)).scalars().all()

    submissions = []
    for s in rows:
        report = s.verification_report or {}
        actions = report.get("actions", [])
        submissions.append(SubmissionSummary(
            id=str(s.id),
            package_name=s.package_name,
            package_registry=s.package_registry,
            package_version=s.package_version,
            source_repo=s.source_repo,
            status=s.status,
            report_status=report.get("status"),
            server_status=(s.server_verification or {}).get("server_status"),
            report_summary=report.get("summary"),
            actions_high=sum(1 for a in actions if a.get("severity") == "high"),
            actions_medium=sum(1 for a in actions if a.get("severity") == "medium"),
            tools_count=len(report.get("tools_snapshot", [])),
            created_at=s.created_at.isoformat() if s.created_at else "",
        ))

    return SubmissionListResponse(submissions=submissions, total=total)


@admin_router.get(
    "/submissions/{submission_id}",
    response_model=SubmissionDetail,
    dependencies=[Depends(rate_limit(30, 60))],
)
async def get_submission(
    submission_id: UUID,
    user: User = Depends(require_admin),
    session: AsyncSession = Depends(get_session),
):
    """Get full submission detail including manifest and report."""
    row = (await session.execute(
        select(McpSubmission).where(McpSubmission.id == submission_id)
    )).scalar_one_or_none()

    if not row:
        raise AppError("MCP_SUBMISSION_NOT_FOUND", "Submission not found", 404)

    ownership = _ownership_view(await _latest_verified_claim(session, row))

    return SubmissionDetail(
        id=str(row.id),
        package_name=row.package_name,
        package_registry=row.package_registry,
        package_version=row.package_version,
        source_repo=row.source_repo,
        status=row.status,
        manifest=row.manifest_raw,
        verification_report=row.verification_report,
        server_verification=row.server_verification,
        ownership=ownership,
        reviewer_notes=row.reviewer_notes,
        maintainer_feedback=row.maintainer_feedback,
        published_package_id=str(row.published_package_id) if row.published_package_id else None,
        created_at=row.created_at.isoformat() if row.created_at else "",
        updated_at=row.updated_at.isoformat() if row.updated_at else "",
    )


@admin_router.put(
    "/submissions/{submission_id}/review",
    response_model=ReviewResponse,
    dependencies=[Depends(rate_limit(10, 60))],
)
async def review_submission(
    submission_id: UUID,
    body: ReviewRequest,
    user: User = Depends(require_admin),
    session: AsyncSession = Depends(get_session),
):
    """Set review status on a submission."""
    if body.status not in ADMIN_VALID_STATUSES:
        raise AppError("MCP_INVALID_STATUS", f"Status must be one of: {', '.join(sorted(ADMIN_VALID_STATUSES))}", 400)

    row = (await session.execute(
        select(McpSubmission).where(McpSubmission.id == submission_id)
    )).scalar_one_or_none()

    if not row:
        raise AppError("MCP_SUBMISSION_NOT_FOUND", "Submission not found", 404)

    row.status = body.status
    row.reviewer_notes = body.notes
    row.maintainer_feedback = body.maintainer_feedback
    row.reviewed_by_id = user.id
    row.reviewed_at = datetime.now(timezone.utc)
    row.updated_at = datetime.now(timezone.utc)

    await session.flush()
    await session.commit()

    logger.info("MCP submission %s reviewed by %s: %s", submission_id, user.email, body.status)

    return ReviewResponse(
        id=str(row.id),
        status=row.status,
        message=f"Submission {row.package_name} marked as {body.status}.",
    )


# ---------------------------------------------------------------------------
# Catalog publication
# ---------------------------------------------------------------------------

class PublishResponse(BaseModel):
    submission_id: str
    package_slug: str
    package_id: str
    message: str


def _verify_publish_gate(submission: McpSubmission, ownership_claim: PublisherPackageClaim | None) -> list[str]:
    """Validate all publish gate rules. Returns list of blocking reasons.

    Three independent axes, never substituted for one another:
    - registry facts (package_exists/version/repo_consistency) from
      ``server_verification`` — authoritative, server-derived;
    - package_control from ``ownership_claim`` (publisher_package_claims) — the
      ONLY source for ownership. repo_consistency must never satisfy it;
    - runtime attestation from the client ``verification_report`` — advisory.
    """
    blocks: list[str] = []

    if submission.status != "approved":
        blocks.append(f"Submission status is '{submission.status}', must be 'approved'")

    if submission.published_package_id is not None:
        blocks.append("Already published")

    manifest = submission.manifest_raw or {}
    if manifest.get("runtime") != "mcp":
        blocks.append("Manifest runtime is not 'mcp'")
    if not isinstance(manifest.get("mcp_server"), dict):
        blocks.append("Manifest missing mcp_server block")

    # --- Server-verified registry facts (authoritative) ---
    sv = submission.server_verification or {}
    if not sv:
        blocks.append("No server verification on record — run re-verify first")
    else:
        sstatus = sv.get("server_status")
        if sstatus == "mismatch":
            reasons = "; ".join(sv.get("errors") or []) or "registry contradicts manifest"
            blocks.append(f"Server verification status is 'mismatch': {reasons}")
        elif sstatus == "unavailable":
            blocks.append("Server verification incomplete (registry was unavailable) — re-verify before publishing")
        if not sv.get("package_exists"):
            blocks.append("Server could not confirm the package exists on the registry")
        if not sv.get("resolved_version"):
            blocks.append("Server could not resolve a published version")
        # repo_consistency: 'mismatch' blocks; 'indeterminate' is allowed (admin warning, not a hard block)
        if sv.get("repo_consistency") == "mismatch":
            blocks.append("source_repo does not match registry metadata (repo_consistency mismatch)")

    # --- Maintainer-attested protocol test (not server-verifiable without execution) ---
    report = submission.verification_report or {}
    if report.get("status") != "TESTED":
        blocks.append(f"Maintainer-attested status is '{report.get('status')}', must be 'TESTED'")

    high_actions = [a for a in report.get("actions", []) if a.get("severity") == "high"]
    if high_actions:
        codes = [a.get("code", "?") for a in high_actions]
        blocks.append(f"Has {len(high_actions)} high-severity action(s): {', '.join(codes)}")

    # --- Package control (ownership) — a SEPARATE axis. repo_consistency must
    # NEVER satisfy this; only a verified, non-expired publisher_package_claim does. ---
    if ownership_claim is None:
        blocks.append("No verified ownership claim — package control is not proven (repo_consistency does not count)")
    elif ownership_claim.expires_at is not None and ownership_claim.expires_at <= datetime.now(timezone.utc):
        blocks.append("Ownership claim has expired — re-verify package control")

    return blocks


@admin_router.post(
    "/submissions/{submission_id}/publish",
    response_model=PublishResponse,
    dependencies=[Depends(rate_limit(5, 60))],
)
async def publish_submission(
    submission_id: UUID,
    user: User = Depends(require_admin),
    session: AsyncSession = Depends(get_session),
):
    """Publish an approved MCP submission to the catalog via publish_package()."""
    from app.packages.models import Package, PackageVersion
    from app.packages.service import publish_package

    row = (await session.execute(
        select(McpSubmission).where(McpSubmission.id == submission_id)
    )).scalar_one_or_none()

    if not row:
        raise AppError("MCP_SUBMISSION_NOT_FOUND", "Submission not found", 404)

    ownership_claim = await _latest_verified_claim(session, row)
    blocks = _verify_publish_gate(row, ownership_claim)
    if blocks:
        raise AppError("MCP_PUBLISH_BLOCKED", "; ".join(blocks), 400)

    # Publish on a copy so the original (audit) submission keeps the raw command.
    # If the server resolved a pinned npm command, the catalog entry uses it for
    # reproducibility (server_verification.pinned_command, npm/npx only).
    manifest = copy.deepcopy(row.manifest_raw)
    pinned_cmd = (row.server_verification or {}).get("pinned_command")
    if pinned_cmd and isinstance(manifest.get("mcp_server"), dict):
        manifest["mcp_server"]["command"] = pinned_cmd
    slug = manifest.get("package_id", row.package_name)
    version = manifest.get("version", row.package_version or "0.1.0")

    # Check if package+version already exists in catalog
    existing = (await session.execute(
        select(PackageVersion.id)
        .join(Package, Package.id == PackageVersion.package_id)
        .where(Package.slug == slug, PackageVersion.version_number == version)
    )).scalar_one_or_none()

    if existing:
        raise AppError(
            "MCP_ALREADY_IN_CATALOG",
            f"{slug}@{version} already exists in the catalog",
            409,
        )

    try:
        pkg, pv, warnings = await publish_package(
            manifest=manifest,
            publisher_id=row.publisher_id,
            session=session,
            artifact_bytes=None,
        )
    except AppError:
        raise
    except Exception as e:
        raise AppError("MCP_PUBLISH_FAILED", f"Publish failed: {e}", 500)

    row.published_package_id = pkg.id
    row.updated_at = datetime.now(timezone.utc)
    await session.commit()

    logger.info("MCP submission %s published as %s by admin %s", submission_id, pkg.slug, user.email)

    return PublishResponse(
        submission_id=str(row.id),
        package_slug=pkg.slug,
        package_id=str(pkg.id),
        message=f"{pkg.slug}@{pv.version_number} published to catalog.",
    )


# ---------------------------------------------------------------------------
# Re-verification (recover from 'unavailable', refresh before approving)
# ---------------------------------------------------------------------------

class ReverifyResponse(BaseModel):
    id: str
    server_status: str | None
    status: str
    message: str


@admin_router.post(
    "/submissions/{submission_id}/reverify",
    response_model=ReverifyResponse,
    dependencies=[Depends(rate_limit(10, 60))],
)
async def reverify_submission(
    submission_id: UUID,
    user: User = Depends(require_admin),
    session: AsyncSession = Depends(get_session),
):
    """Re-run server-side registry verification for a submission.

    Recovers submissions stuck on ``unavailable`` (registry was down at submit
    time) and lets an admin refresh the registry facts before approving. Does not
    touch already-published or admin-decided submissions beyond refreshing facts;
    re-derives status only while still in the open queue.
    """
    row = (await session.execute(
        select(McpSubmission).where(McpSubmission.id == submission_id)
    )).scalar_one_or_none()

    if not row:
        raise AppError("MCP_SUBMISSION_NOT_FOUND", "Submission not found", 404)

    sv = await verify_registry(row.manifest_raw or {})
    row.server_verification = sv
    if sv.get("resolved_version"):
        row.package_version = sv["resolved_version"]
    if row.status in ("pending", "action_required"):
        row.status = derive_status(sv, row.verification_report or {})
    row.updated_at = datetime.now(timezone.utc)
    await session.commit()

    logger.info(
        "MCP submission %s re-verified by %s: server=%s status=%s",
        submission_id, user.email, sv.get("server_status"), row.status,
    )

    return ReverifyResponse(
        id=str(row.id),
        server_status=sv.get("server_status"),
        status=row.status,
        message=f"Re-verified: server status '{sv.get('server_status')}', submission now '{row.status}'.",
    )


# ---------------------------------------------------------------------------
# Ownership (package_control) — manual admin verification (Step 1)
# ---------------------------------------------------------------------------

class VerifyOwnershipRequest(BaseModel):
    reason: str = Field(..., min_length=1, description="Audit reason for the manual ownership decision")


class VerifyOwnershipResponse(BaseModel):
    claim_id: str
    status: str
    message: str


@admin_router.post(
    "/submissions/{submission_id}/verify-ownership",
    response_model=VerifyOwnershipResponse,
    dependencies=[Depends(rate_limit(10, 60))],
)
async def verify_ownership_manual(
    submission_id: UUID,
    body: VerifyOwnershipRequest,
    user: User = Depends(require_admin),
    session: AsyncSession = Depends(get_session),
):
    """Admin explicitly attests package ownership (method=manual_admin).

    This satisfies the ownership (package_control) dimension of the publish gate
    for this publisher+package. It is an explicit, audited decision — NOT derived
    from repo_consistency. Creates a time-bounded verified claim.
    """
    row = (await session.execute(
        select(McpSubmission).where(McpSubmission.id == submission_id)
    )).scalar_one_or_none()
    if not row:
        raise AppError("MCP_SUBMISSION_NOT_FOUND", "Submission not found", 404)

    now = datetime.now(timezone.utc)
    claim = PublisherPackageClaim(
        id=uuid4(),
        publisher_id=row.publisher_id,
        registry=row.package_registry,
        package_name=row.package_name,
        package_name_normalized=normalize_package_name(row.package_registry, row.package_name),
        method="manual_admin",
        strength="manual",
        status="verified",
        evidence={"basis": "manual_admin", "submission_id": str(submission_id), "reason": body.reason},
        verified_at=now,
        verified_by_id=user.id,
        expires_at=now + timedelta(days=OWNERSHIP_CLAIM_TTL_DAYS),
    )
    session.add(claim)
    await session.flush()
    await session.commit()

    logger.info(
        "MCP ownership manually verified: %s/%s by admin %s (claim %s)",
        row.package_registry, row.package_name, user.email, claim.id,
    )

    return VerifyOwnershipResponse(
        claim_id=str(claim.id),
        status="verified",
        message=f"Ownership of {row.package_name} marked manually verified (audited).",
    )
