"""MCP submission endpoints."""
import logging
from uuid import uuid4

from fastapi import APIRouter, Depends
from pydantic import BaseModel, Field
from sqlalchemy.ext.asyncio import AsyncSession

from app.auth.dependencies import require_publisher
from app.auth.models import User
from app.database import get_session
from app.shared.exceptions import AppError
from app.shared.rate_limit import rate_limit
from app.mcp.models import McpSubmission

router = APIRouter(prefix="/v1/mcp", tags=["mcp"])
logger = logging.getLogger(__name__)

VALID_STATUSES = {"INVALID", "RESOLVED", "TESTED", "REVIEW_NEEDED", "MAINTAINER_ACTION_REQUIRED"}


class McpSubmitRequest(BaseModel):
    manifest: dict = Field(..., description="agentnode.yaml manifest (v0.3, runtime=mcp)")
    verification_report: dict = Field(..., description="Output of agentnode mcp verify --json")


class McpSubmitResponse(BaseModel):
    id: str
    status: str
    package_name: str
    message: str


@router.post(
    "/submit",
    response_model=McpSubmitResponse,
    status_code=201,
    dependencies=[Depends(rate_limit(5, 60))],
)
async def submit_mcp(
    body: McpSubmitRequest,
    user: User = Depends(require_publisher),
    session: AsyncSession = Depends(get_session),
):
    """Submit an MCP server for catalog review.

    Accepts a manifest and its verification report. The report must have been
    generated by `agentnode mcp verify --json`. No code is executed server-side.
    """
    manifest = body.manifest
    report = body.verification_report

    if manifest.get("runtime") != "mcp":
        raise AppError("MCP_INVALID_RUNTIME", "Manifest runtime must be 'mcp'", 400)

    mcp_server = manifest.get("mcp_server")
    if not isinstance(mcp_server, dict):
        raise AppError("MCP_MISSING_SERVER", "Manifest must have mcp_server block", 400)

    report_status = report.get("status", "")
    if report_status not in VALID_STATUSES:
        raise AppError("MCP_INVALID_REPORT", f"Verification report status '{report_status}' is not valid", 400)

    if report_status == "INVALID":
        raise AppError("MCP_REPORT_INVALID", "Cannot submit with INVALID verification status. Fix errors first.", 400)

    pkg_name = mcp_server.get("npm_package") or mcp_server.get("pypi_package") or "unknown"
    pkg_registry = "npm" if mcp_server.get("npm_package") else "pypi"
    pkg_version = report.get("package", {}).get("version")
    source_repo = mcp_server.get("source_repo")

    submission = McpSubmission(
        id=uuid4(),
        publisher_id=user.publisher.id,
        package_name=pkg_name,
        package_registry=pkg_registry,
        package_version=pkg_version,
        source_repo=source_repo,
        manifest_raw=manifest,
        verification_report=report,
        status="pending" if report_status in ("TESTED", "RESOLVED") else "action_required",
    )
    session.add(submission)
    await session.flush()
    await session.commit()

    logger.info("MCP submission %s by publisher %s: %s (%s)", submission.id, user.publisher.slug, pkg_name, submission.status)

    if submission.status == "pending":
        msg = f"Submission received. {pkg_name} is queued for catalog review."
    else:
        actions = report.get("actions", [])
        high_count = sum(1 for a in actions if a.get("severity") == "high")
        msg = f"Submission received with {high_count} required action(s). Fix and resubmit for faster review."

    return McpSubmitResponse(
        id=str(submission.id),
        status=submission.status,
        package_name=pkg_name,
        message=msg,
    )
