import type { Metadata } from "next";
import {
  DocsShell,
  DocsJsonLd,
  SubHeading,
  CodeBlock,
  C,
} from "@/components/docs";

const TITLE = "Installing Packages";
const DESCRIPTION = "What happens on agentnode install: version resolution, SHA-256 verification, the lockfile format, loading tools in Python, updates and rollback.";
const PATH = "/docs/packages";

export const metadata: Metadata = {
  title: "Installing Packages — Docs | AgentNode",
  description: DESCRIPTION,
  alternates: { canonical: PATH },
  openGraph: {
    title: "Installing Packages — Docs | AgentNode",
    description: DESCRIPTION,
    type: "website",
    url: PATH,
    siteName: "AgentNode",
  },
};

export default function Page() {
  return (
    <>
      <DocsJsonLd title={TITLE} description={DESCRIPTION} path={PATH} />
      <DocsShell title={TITLE}>
          <section>

            <SubHeading>Basic installation</SubHeading>
            <CodeBlock title="terminal">{`$ agentnode install pdf-reader-pack

Installing pdf-reader-pack@1.2.0...
  Downloading package       done
  Verifying hash (SHA-256)  done
  Installing dependencies   done
  Writing lockfile           done

Installed pdf-reader-pack@1.2.0`}</CodeBlock>

            <SubHeading>Install a specific version</SubHeading>
            <CodeBlock title="terminal">{`$ agentnode install pdf-reader-pack@1.1.0`}</CodeBlock>

            <SubHeading>Install multiple packs</SubHeading>
            <CodeBlock title="terminal">{`$ agentnode install pdf-reader-pack web-search-pack email-drafter-pack`}</CodeBlock>

            <SubHeading>What happens during installation</SubHeading>
            <p className="mb-3 text-sm text-muted">
              When you run <C>agentnode install</C>, the following steps execute
              in order:
            </p>
            <ol className="mb-4 list-inside list-decimal space-y-2 text-sm text-muted">
              <li>
                <span className="text-foreground/80 font-medium">
                  Version resolution
                </span>{" "}
                -- the registry resolves the latest compatible version (or the
                pinned version you specified).
              </li>
              <li>
                <span className="text-foreground/80 font-medium">
                  Download
                </span>{" "}
                -- the package archive is downloaded from the registry.
              </li>
              <li>
                <span className="text-foreground/80 font-medium">
                  Hash verification
                </span>{" "}
                -- the downloaded archive is verified against the SHA-256 hash
                stored in the registry. If the hash does not match, the install
                is aborted.
              </li>
              <li>
                <span className="text-foreground/80 font-medium">
                  Dependency installation
                </span>{" "}
                -- Python dependencies declared in the pack are installed via
                pip.
              </li>
              <li>
                <span className="text-foreground/80 font-medium">
                  Lockfile update
                </span>{" "}
                -- the pack version and hash are recorded in{" "}
                <C>agentnode.lock</C> for reproducible installations.
              </li>
            </ol>

            <SubHeading>The lockfile</SubHeading>
            <p className="mb-3 text-sm text-muted">
              The <C>agentnode.lock</C> file records exactly which versions and
              hashes are installed. Commit this file to version control for
              reproducible builds across environments.
            </p>
            <CodeBlock title="agentnode.lock" language="yaml">{`# Auto-generated by agentnode. Do not edit manually.
lockfile_version: 2

packages:
  csv-analyzer-pack:
    version: "1.1.0"
    hash: "sha256:a1b2c3d4e5f6..."
    installed_at: "2025-01-15T10:30:00Z"
    entrypoint: "csv_analyzer_pack.tool"
    tools:
      - name: "describe"
        entrypoint: "csv_analyzer_pack.tool:describe"
        capability_id: "csv_analysis"
      - name: "filter"
        entrypoint: "csv_analyzer_pack.tool:filter_rows"
        capability_id: "data_cleaning"

  pdf-reader-pack:
    version: "1.2.0"
    hash: "sha256:f6e5d4c3b2a1..."
    installed_at: "2025-01-15T10:31:00Z"
    entrypoint: "pdf_reader_pack.tool"
    tools: []`}</CodeBlock>

            <SubHeading>Using packs in code</SubHeading>
            <p className="mb-3 text-sm text-muted">
              Every pack is loaded through the SDK&apos;s <C>load_tool()</C> function.
              v0.2 packs support multiple tools with individual entrypoints.
              v0.1 packs work the same way with a single default entrypoint.
            </p>
            <CodeBlock title="agent.py" language="python">{`from agentnode_sdk.installer import load_tool

# v0.2 multi-tool pack — load specific tools by name
describe = load_tool("csv-analyzer-pack", tool_name="describe")
filter_rows = load_tool("csv-analyzer-pack", tool_name="filter")

result = describe({"file_path": "data.csv"})
filtered = filter_rows({"file_path": "data.csv", "column": "status", "value": "active"})

# v0.1 single-tool packs — no tool_name needed
extract = load_tool("pdf-reader-pack")
pdf_result = extract({"file_path": "report.pdf"})

search = load_tool("web-search-pack")
search_result = search({"query": "AgentNode", "max_results": 5})`}</CodeBlock>

            <SubHeading>Updating and rolling back</SubHeading>
            <CodeBlock title="terminal">{`# Update to latest version
$ agentnode update pdf-reader-pack
Updating pdf-reader-pack 1.2.0 -> 1.3.0... done

# Roll back to a specific version
$ agentnode rollback pdf-reader-pack@1.2.0
Rolling back pdf-reader-pack 1.3.0 -> 1.2.0... done

# List all installed packs
$ agentnode list
Installed packages:
  pdf-reader-pack    v1.0.0  trusted
  web-search-pack    v1.0.0  trusted`}</CodeBlock>
          </section>
      </DocsShell>
    </>
  );
}
